config/routes.rb
Rails.application.routes.draw do
  post 'proyectos/create'
  get 'proyectos/dashboard'
  get 'proyectos/new'
  root 'proyectos#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
    validates :name, :description, :state, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  def create
    @project = Proyecto.create(name: params[:name],
                        description: params[:description],
                        date_start: params[:date_start],
                        date_end: params[:date_end],
                        state: params[:state])
  end

  def dashboard
    if params[:state].present?
      @projects = Proyecto.where('state = ?', params[:state])
    else
      @projects = Proyecto.all
    end
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gestor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container p-5">
    <%= yield %>
  </div>
  </body>
</html>

app/views/proyectos/create.html.erb
<%= link_to 'Volver al Inicio', root_path %><br>
<%= link_to 'Ver proyectos', proyectos_dashboard_path %><br>

<% if @project.errors.any? %>
    <div id="error_explanation">
        <h2>No se pudo crear el proyecto, por las siguientes razones:</h2>
        <ul>
            <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
    <% else %>
    <h1>¡El proyecto ha sido guardado con exito!</h1>
<% end  %>

app/views/proyectos/dashboard.html.erb
<%= link_to 'Volver al Inicio', root_path %><br>

<form>
    <label for="state">Estado</label>
    <select name="state">
        <option value="propuesta">Propuesta</option>
        <option value="progreso">En progreso</option>
        <option value="terminado">Terminado</option>
    </select>
    <button type="submit" class="btn btn-primary">Buscar</button>
</form>

<table class="table">
    <tr>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Fecha de Inicio</th>
        <th>Fecha de Término</th>
        <th>Estado</th>
    </tr>
    <% @projects.each do |p| %>
        <tr>
            <td><%= p.name %></td>
            <td><%= p.description %></td>
            <td><%= p.date_start %></td>
            <td><%= p.date_end %></td>
            <td><%= p.state %></td>
        </tr>
    <% end %>
</table>

app/views/proyectos/new.html.erb
<%= link_to 'Ir al Dashboard', proyectos_dashboard_path %><br>

<form action="/proyectos/create" method="POST">
    <%= token_tag %>

    <div class="form-group">
        <label for="name">Nombre</label>
        <input name="name" class="form-control">
    </div>

    <div class="form-group">
        <label for="description">Descripcion</label>
        <input name="description" class="form-control">
    </div>

    <div class="form-group">
        <label for="date_start">Fecha de Inicio</label>
        <input type="date" name="date_start" class="form-control">
    </div>

    <div class="form-group">
        <label for="date_end">Fecha de Término</label>
        <input type="date" name="date_end" class="form-control">
    </div>

    <div class="form-group">
        <label for="state">Estado</label>
        <select name="state">
            <option value="propuesta" selected >Propuesta</option>
            <option value="progreso">En progreso</option>
            <option value="terminado">Terminado</option>
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Crear</button>
</form>